### ISSUE TITLE
modules showing "changed" even though nothing was done due to missing access_token

### ISSUE THREAD

**Issue by jantari** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#134]
Hi,

I am using the `fortinet.fortios` collection `2.1.2` to configure a Fortigate 40F using an api-user and an api-key/access-token to authenticate.

I had some tasks in the beginning of my playbook where I added the `access_token`, but on some later tasks (that were included from a separate tasks file) I forgot - the tasks from that file were still run and showed a "changed" status from ansible, however nothing was actually changed on the firewall. It took me a long time to figure it out, but turns out it was because I forgot the `access_token` - after addingthe `access_token` to those tasks as well they still showed "changed" but now the change was actually made on the firewall.

I think tasks that fail due to missing `access_token` aka authentication should *FAIL* and not show "changed".

To reproduce:

- Fortigate 40F with Firmware 6.4.4
- ansible 2.11.2 with fortinet.fortios collection 2.1.2

My Playbook:

    ---

    - hosts: all
      gather_facts: no
      connection: httpapi
      collections:
      - fortinet.fortios
      vars:
        vdom: "root"
        fortios_access_token: $SECRET_ACCESS_TOKEN
        timezone: '26'
      tasks:
      - name: Get firwall system status as a test
        fortios_configuration_fact:
          vdom: "{{ vdom }}"
          access_token: "{{ fortios_access_token | default(omit) }}"
          selector: system_status
        register: _system_status

      - name: Print firewall system status
        debug:
          msg: "{{ _system_status }}"

      - name: Configure hostname
        fortios_system_global:
          vdom: "{{ vdom }}"
          access_token: "{{ fortios_access_token | default(omit) }}"
          system_global:
            hostname: "{{ inventory_hostname | lower }}"
        when: not ansible_check_mode

      - name: Configure timezone
        fortios_system_global:
          vdom: "{{ vdom }}"
          access_token: "{{ fortios_access_token | default(omit) }}"
          system_global:
            timezone: "{{ timezone }}"
        when: not ansible_check_mode

      - name: Configure objects
        include_tasks: tasks/all/objects.yml

The tasks/all/objects.yml file:

    ---

    - name: Configure address objects
      fortios_firewall_address:
        vdom: "{{ vdom }}"
        state: present
        firewall_address:
          name: "{{ item.name }}"
          subnet: "{{ item.subnet }}"
          comment: "{{ item.comment | default(omit) }}"
      loop:
        - name: Test_Address_1
          subnet: 10.1.0.0/24
          comment: Test_Address_1_Comment
        - name: Test_Address_2
          subnet: 10.2.0.0/24
          comment: Test_Address_2_Comment
        - name: Test_Address_3
          subnet: 10.3.0.0/24
          comment: Test_Address_3_Comment
        - name: Test_Address_4
          subnet: 10.4.0.0/24
          comment: Test_Address_4_Comment
      loop_control:
        label: "{{ item.name }}"

When running this the output is:

    TASK [Configure address objects] ****************************************************************************************************************************************************
    changed: [my40f] => (item=Test_Address_1)
    changed: [my40f] => (item=Test_Address_1)
    changed: [my40f] => (item=Test_Address_1)
    changed: [my40f] => (item=Test_Address_1)

However verifying with the WebUI or CLI, the objects have not been created. Adding:

    access_token: "{{ fortios_access_token | default(omit) }}"

to the `fortios_firewall_address` task fixes this, but without a valid access token the task should fail.

**Comment by JieX19** [comment]
Hi @jantari,

For the first question, the basic logic of authentication is that the access_token has higher priority than using username and password. If access_token is not detected then the username + password will be used for the authentication, which answers the question you mentioned above that the task is executed ' even though access_token is omitted.

I tried the same playbook(tasks/all/objects.yml file) on my side and it runs successfully (without using access_token). 
<img width="783" alt="no_accesstoken_results" src="https://user-images.githubusercontent.com/59745792/135906401-350c227e-2ddc-4206-b521-c7fb43040904.PNG">

Can you please try the  tasks/all/objects.yml file you wrote above and send me a copy of the results. CLI or GUI both works.

Thanks!

**Comment by jantari** [comment]
Hi,

> the access_token has higher priority than using username and password. If access_token is not detected then the username + password will be used for the authentication, which answers the question you mentioned above that the task is executed ' even though access_token is omitted.

Thanks, I understand that `access_token` has a higher priority but in my playbook and variable files I have no `ansible_password` defined for this firewall so it is "undefined" and could not be used for authentication.

The current situation with my inventory is that some firewalls (our PoC models) were authenticated against with username + password, so I have `ansible_user` set to "ansible" in the `group_vars/all.yml` file - so that sets it for all firewalls. However the password was different per-firewall so `ansible_password` was set in each firewalls individual `host_vars/firewallname.yml` file. This worked.

Then I started using access tokens, so for those firewalls I do not have a `ansible_password` set in their inventory file, only an `access_token`. I hope that makes it clearer.

I just tried again and was able to reproduce the problem again. I could send you the results of the task but it's not that interesting - the objects are just missing. There are a bunch of internal address objects I'd have to redact too - not sure if it'd still be helpful?

**Comment by JieX19** [comment]
Can you help check the default inventory file under /etc/ansible/hosts to see if there's any configs in this file. Because authentication is required to access to a Forti_Device. It must be set up somewhere, otherwise, you will definitely get an error saying **"ansible.module_utils.connection.ConnectionError: Please provide access token or username/password to login"**. 
Here's an example:
```
[fortigates]
fortigate01 enable_log=True ansible_host=192.168.23.12 ansible_user=admin ansible_password=123

[fortigates:vars]
ansible_network_os=fortinet.fortios.fortios
access_token=rw0rc31ffqd83p1c0Hjtcfrl0nwf4g
```

For the above playbooks, what tasks are configured successfully? and which one is failed? It also helps me investigate the case. Because I can run the same playbook on my side and everything returns successfully.

The results seem pointless now. Can you send me the debugging log using the following command? From which we can get more internal info for the request.

Verbose output can help with debugging. To enable verbose debugging, use the following commands in the FortiGate CLI:

diagnose debug enable
diagnose debug application httpsd -1

**Comment by JieX19** [comment]
@jantari Thanks for the updates! I will look into the case and get back to you once it's confirmed and fixed.

**Comment by JieX19** [comment]
@jantari Finally I reproduce the issue. I have fixed it and it will be covered in the upcoming release. Thank you!

**Comment by JieX19** [comment]
Hi @jantari 

The error is fixed in the new release 2.1.3. Thanks for raising the issue! Let me know if you have any other questions.

**Comment by JieX19** [comment]
Using command **ansible-galaxy collection install fortinet.fortios:2.1.3**

**Comment by jantari** [comment]
I will be able to test it on monday. btw, when going to the "latest" documentation at https://ansible-galaxy-fortios-docs.readthedocs.io/en/latest/ it still shows 2.1.2 and not 2.1.3. I have to manually select `v: galaxy-2.1.3` in the bottom left to see the updated release notes and documentation.

**Comment by JieX19** [comment]
@jantari The latest version is 2.1.3 now. Thanks!

**Comment by jantari** [comment]
I tested version 2.1.3 today and indeed the tasks fail now - thanks! 👍 

```yaml
failed: [my40f] (item=Test_Address_1) => changed=false
  ansible_loop_var: item
  item:
    comment: Test_Address_1_Comment
    name: Test_Address_1
    subnet: 10.1.0.0/24
  meta:
    http_status: 401
    raw: |-
      <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
      <html><head>
      <title>401 Unauthorized</title>
      </head><body>
      <h1>Unauthorized</h1>
      <p>This server could not verify that you
      are authorized to access the document
      requested.  Either you supplied the wrong
      credentials (e.g., bad password), or your
      browser doesn't understand how to supply
      the credentials required.</p>
      <p>Additionally, a 401 Unauthorized
      error was encountered while trying to use an ErrorDocument to handle the request.</p>
      </body></html>
  msg: Error in repo
```
