### ISSUE TITLE
We (the ansible steering commitee) see some problems with this collection

### ISSUE THREAD

**Issue by mariolenz** [fortinet-ansible-dev/ansible-galaxy-fortios-collection#287]
We (the ansible steering commitee) see some problems with this collection. One thing is the sheer size of the collection. But we see some other problems, too.

At the moment, we are discussing if we should remove this collection from the community package. It would be great if you could join the [discussion](https://forum.ansible.com/t/should-we-keep-the-fortinet-collections-fortinet-fortimanager-fortinet-fortios-in-the-community-ansible-package).

After all, we might be wrong :shrug:

**Comment by lix-fortinet** [comment]
Hi @mariolenz,

Thank you for letting us know. We will join the discussion and improve our collection to fix these problems.

Happy New Year!

Thanks,
Xing

**Comment by JieX19** [comment]
Hi Ansible team,

I'll proceed to close this ticket as the issues mentioned in this thread are already fixed. Feel free to reopen it if you have any other questions.

Thanks,
Jie

**Comment by mariolenz** [comment]
@felixfontein I've opened the issue, but you've started the discussion in the forum. So I wanted to ping you and make you aware that this has been closed.

So I think you should have a look at this. IIRC we were were fine with the changes, but I'm not 100% sure. If you think they're not, please re-open this or open a new issue.

**Comment by felixfontein** [comment]
@JieX19 is there an update on the basic CI / sanity tests? I still don't see any CI in this repository.
